apiVersion: apps/v1
kind: Deployment
metadata:
  name: appdemo
  namespace: app
  labels:
    app: appdemo-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appdemo-monitoring
  template:
    metadata:
      labels:
        app: appdemo-monitoring

    spec:
      containers:
        - name: appdemo
          image: troynguyeen/demoapp
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              memory: 500Mi
              cpu: 250m
            limits:
              memory: 1Gi
              cpu: 500m
      # nodeSelector:
      #   app: demoapp