apiVersion: v1
kind: Service
metadata:
  namespace: app
  name: appdemo-svc
  labels:
    app: appdemo-monitoring
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: http
  selector:
    app: appdemo-monitoring