apiVersion: apps/v1
kind: Deployment
metadata:
  name: appdemo-v1
  namespace: demo
  labels:
    app: appdemo-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appdemo
      version: v1
  template:
    metadata:
      labels:
        app: appdemo
        version: v1

    spec:
      containers:
        - name: appdemo
          image: troynguyeen/demoapp
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              memory: 256Mi
              cpu: 200m
            limits:
              memory: 256Mi
              cpu: 200m