apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: appdemo-podmonitor
  namespace: demo
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - demo
  selector:
    matchLabels:
      app: appdemo-monitoring
  podMetricsEndpoints:
    - port: http
      path: /actuator/prometheus